# Generated by Django 4.2 on 2024-04-14 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=255)),
                ('skin_type', models.CharField(max_length=255)),
                ('skin_concerns', models.CharField(max_length=255)),
                ('react_to_new_products', models.CharField(max_length=255)),
                ('sleep_cycle', models.CharField(blank=True, max_length=255, null=True)),
                ('skincare_texture', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
