# Generated by Django 5.0.3 on 2024-04-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=255)),
                ('skin_type', models.CharField(max_length=255)),
                ('skin_concerns', models.CharField(max_length=255)),
                ('react_to_new_products', models.CharField(max_length=255)),
                ('sensitive', models.CharField(max_length=255)),
                ('sleep_cycle', models.CharField(max_length=255)),
                ('skincare_texture', models.CharField(max_length=255)),
            ],
        ),
    ]
