# Generated by Django 5.0.3 on 2024-04-14 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizmodel',
            name='sensitive',
        ),
    ]
