# Generated by Django 5.0.3 on 2024-04-16 17:47

import django.db.models.deletion
import utils.helpers.image_file_path
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ReactToNewProductsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('react_to_new_products', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SkinCareTextureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_texture', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SkinConernModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_concern', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SkinTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SleepCycleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_cycle', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SunscreenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('essentials', models.TextField()),
                ('image1', models.ImageField(upload_to=utils.helpers.image_file_path.sunscreen_image)),
                ('image2', models.ImageField(upload_to=utils.helpers.image_file_path.sunscreen_image)),
                ('description', models.TextField()),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skin_treatment.agemodel')),
                ('react_to_new_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skin_treatment.reacttonewproductsmodel')),
                ('skin_concern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skin_treatment.skinconernmodel')),
                ('skin_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skin_treatment.skintypemodel')),
                ('skincare_texture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skin_treatment.skincaretexturemodel')),
                ('sleep_cycle', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='skin_treatment.sleepcyclemodel')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skin_treatment.treatmentmodel')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SerumModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('essentials', models.TextField()),
                ('image1', models.ImageField(upload_to=utils.helpers.image_file_path.serum_image)),
                ('image2', models.ImageField(upload_to=utils.helpers.image_file_path.serum_image)),
                ('description', models.TextField()),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skin_treatment.agemodel')),
                ('react_to_new_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skin_treatment.reacttonewproductsmodel')),
                ('skincare_texture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skin_treatment.skincaretexturemodel')),
                ('skin_concern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skin_treatment.skinconernmodel')),
                ('skin_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skin_treatment.skintypemodel')),
                ('sleep_cycle', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='skin_treatment.sleepcyclemodel')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skin_treatment.treatmentmodel')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NaturalProductsSerumModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('serum1', models.CharField(max_length=100)),
                ('serum1_image', models.ImageField(upload_to=utils.helpers.image_file_path.serum_image)),
                ('serum1_application', models.TextField()),
                ('serum1_benefits', models.TextField()),
                ('serum2', models.CharField(max_length=100)),
                ('serum2_image', models.ImageField(upload_to=utils.helpers.image_file_path.serum_image)),
                ('serum2_application', models.TextField()),
                ('serum2_benefits', models.TextField()),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skin_treatment.treatmentmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NaturalProductsScrubModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('scrub1', models.CharField(max_length=100)),
                ('scrub1_preperation', models.TextField()),
                ('scrub1_image', models.ImageField(upload_to=utils.helpers.image_file_path.scrub_image)),
                ('scrub1_application', models.TextField()),
                ('scrub1_benefits', models.TextField()),
                ('scrub2', models.CharField(max_length=100)),
                ('scrub2_preperation', models.TextField()),
                ('scrub2_image', models.ImageField(upload_to=utils.helpers.image_file_path.scrub_image)),
                ('scrub2_application', models.TextField()),
                ('scrub2_benefits', models.TextField()),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skin_treatment.treatmentmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NaturalProductsMoisturizerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('moisturizer1', models.CharField(max_length=100)),
                ('moisturizer1_image', models.ImageField(upload_to=utils.helpers.image_file_path.moisturizer_image)),
                ('moisturizer1_application', models.TextField()),
                ('moisturizer1_benefits', models.TextField()),
                ('moisturizer2', models.CharField(max_length=100)),
                ('moisturizer2_image', models.ImageField(upload_to=utils.helpers.image_file_path.moisturizer_image)),
                ('moisturizer2_application', models.TextField()),
                ('moisturizer2_benefits', models.TextField()),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skin_treatment.treatmentmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NaturalProductsFacewashModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('disclaimer', models.TextField()),
                ('facewash1', models.CharField(max_length=100)),
                ('facewash1_image', models.ImageField(upload_to=utils.helpers.image_file_path.facewash_image)),
                ('facewash1_application', models.TextField()),
                ('facewash1_benefits', models.TextField()),
                ('facewash2', models.CharField(max_length=100)),
                ('facewash2_image', models.ImageField(upload_to=utils.helpers.image_file_path.facewash_image)),
                ('facewash2_application', models.TextField()),
                ('facewash2_benefits', models.TextField()),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skin_treatment.treatmentmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NaturalProductsFacemaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('facemask1', models.CharField(max_length=100)),
                ('facemask1_image', models.ImageField(upload_to=utils.helpers.image_file_path.facemask_image)),
                ('facemask1_application', models.TextField()),
                ('facemask1_benefits', models.TextField()),
                ('facemask2', models.CharField(max_length=100)),
                ('facemask2_image', models.ImageField(upload_to=utils.helpers.image_file_path.facemask_image)),
                ('facemask2_application', models.TextField()),
                ('facemask2_benefits', models.TextField()),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skin_treatment.treatmentmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MoisturizerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('essentials', models.TextField()),
                ('image1', models.ImageField(upload_to=utils.helpers.image_file_path.moisturizer_image)),
                ('image2', models.ImageField(upload_to=utils.helpers.image_file_path.moisturizer_image)),
                ('description', models.TextField()),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skin_treatment.agemodel')),
                ('react_to_new_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skin_treatment.reacttonewproductsmodel')),
                ('skincare_texture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skin_treatment.skincaretexturemodel')),
                ('skin_concern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skin_treatment.skinconernmodel')),
                ('skin_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skin_treatment.skintypemodel')),
                ('sleep_cycle', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='skin_treatment.sleepcyclemodel')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skin_treatment.treatmentmodel')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FaceWashModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('essentials', models.TextField()),
                ('image1', models.ImageField(upload_to=utils.helpers.image_file_path.facewash_image)),
                ('image2', models.ImageField(upload_to=utils.helpers.image_file_path.facewash_image)),
                ('description', models.TextField()),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skin_treatment.agemodel')),
                ('react_to_new_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skin_treatment.reacttonewproductsmodel')),
                ('skincare_texture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skin_treatment.skincaretexturemodel')),
                ('skin_concern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skin_treatment.skinconernmodel')),
                ('skin_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skin_treatment.skintypemodel')),
                ('sleep_cycle', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='skin_treatment.sleepcyclemodel')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skin_treatment.treatmentmodel')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
