# Generated by Django 5.0.3 on 2024-04-12 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_treatment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facewashmodel',
            name='sleep_cycle',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='skin_treatment.sleepcyclemodel'),
        ),
        migrations.AlterField(
            model_name='moisturizermodel',
            name='sleep_cycle',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='skin_treatment.sleepcyclemodel'),
        ),
        migrations.AlterField(
            model_name='serummodel',
            name='sleep_cycle',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='skin_treatment.sleepcyclemodel'),
        ),
        migrations.AlterField(
            model_name='sunscreenmodel',
            name='sleep_cycle',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='skin_treatment.sleepcyclemodel'),
        ),
    ]
