# Generated by Django 5.0.3 on 2024-04-17 06:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_treatment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agemodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='naturalproductsfacemaskmodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='naturalproductsfacewashmodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='naturalproductsmoisturizermodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='naturalproductsscrubmodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='naturalproductsserummodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='reacttonewproductsmodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='skincaretexturemodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='skinconernmodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='skintypemodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='sleepcyclemodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='treatmentmodel',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='agemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agemodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reacttonewproductsmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reacttonewproductsmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reacttonewproductsmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='skincaretexturemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skincaretexturemodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='skincaretexturemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='skinconernmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skinconernmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='skinconernmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='skintypemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skintypemodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='skintypemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sleepcyclemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sleepcyclemodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sleepcyclemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='treatmentmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatmentmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='treatmentmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
