# Generated by Django 5.0.3 on 2024-04-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_treatment', '0002_alter_agemodel_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleepcyclemodel',
            name='sleep_cycle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
