# Generated by Django 5.0.3 on 2024-04-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_treatment', '0002_alter_facewashmodel_sleep_cycle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensitivemodel',
            name='senstive',
            field=models.CharField(max_length=20),
        ),
    ]
