# Generated by Django 4.2 on 2024-04-12 16:31

from django.db import migrations, models
import utils.helpers.image_file_path


class Migration(migrations.Migration):

    dependencies = [
        ('skin_treatment', '0003_alter_sensitivemodel_senstive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moisturizermodel',
            name='image1',
            field=models.ImageField(upload_to=utils.helpers.image_file_path.serum_image),
        ),
        migrations.AlterField(
            model_name='moisturizermodel',
            name='image2',
            field=models.ImageField(upload_to=utils.helpers.image_file_path.serum_image),
        ),
        migrations.AlterField(
            model_name='serummodel',
            name='image1',
            field=models.ImageField(upload_to=utils.helpers.image_file_path.moisturizer_image),
        ),
        migrations.AlterField(
            model_name='serummodel',
            name='image2',
            field=models.ImageField(upload_to=utils.helpers.image_file_path.moisturizer_image),
        ),
    ]
