# Generated by Django 5.0.3 on 2024-04-14 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skin_treatment', '0003_alter_sleepcyclemodel_sleep_cycle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sunscreenmodel',
            name='senstive',
        ),
        migrations.RemoveField(
            model_name='facewashmodel',
            name='senstive',
        ),
        migrations.RemoveField(
            model_name='moisturizermodel',
            name='senstive',
        ),
        migrations.RemoveField(
            model_name='serummodel',
            name='senstive',
        ),
        migrations.DeleteModel(
            name='SensitiveModel',
        ),
    ]
